#!/bin/sh


# exit script on any error
set -e
echo "setting up initial configurations"

if [ ! -f "$KVD_HOME/config/config.toml" ];
then

  kvd init ${MONIKER:-nonamenode} --home=${KVD_HOME:-/.kvd} --chain-id=${CHAIN_ID:-kava-4}

  cd $KVD_HOME/config

  echo "removing autogenerated genesis and config files"
  rm genesis.json
  rm config.toml
  rm app.toml


  echo "downloading genesis.json"

  if [ ! -z "$GENESIS_URL" ]; then
      wget $GENESIS_URL
  else
      wget https://raw.githubusercontent.com/Kava-Labs/launch/master/kava-4/genesis.json
  fi

echo "generating config.toml"

cat > config.toml << EOF
proxy_app = "${PROXY_APP:-tcp://0.0.0.0}:${PROXY_APP_PORT:-26658}"
moniker = "${MONIKER:-moniker}"
fast_sync = ${FAST_SYNC:-true}
db_backend = "${DB_BACKEND:-goleveldb}"
db_dir = "${DB_DIR:-data}"
log_level = "${LOG_LEVEL:-main:info,state:info,*:error}"
log_format = "${LOG_FORMAT:-plain}"
genesis_file = "${GENESIS_FILE:-config/genesis.json}"
priv_validator_key_file = "${PRIV_VALIDATOR_KEY_FILE:-config/priv_validator_key.json}"
priv_validator_state_file = "${PRIV_VALIDATOR_KEY_FILE:-data/priv_validator_state.json}"
priv_validator_laddr = "${PRIV_VALIDATOR_LADDR:-}"
node_key_file = "${NODE_KEY_FILE:-config/node_key.json}"
abci = "${ABCI:-socket}"
prof_laddr = "${PROF_LADDR:-localhost:6060}"
filter_peers = ${FILTER_PEERS:-false}


[rpc]
laddr = "${RPC_LADDR:-tcp://0.0.0.0}:${RPC_PORT:-26657}"
cors_allowed_origins = ["${CORS_ALLOWED_ORIGINS:-*}"]
cors_allowed_methods = ["HEAD", "GET", "POST"]
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]
grpc_laddr = "${GRPC_LADDR:-}"
grpc_max_open_connections = ${GRPC_MAX_OPEN_CONNECTIONS:-900}
unsafe = ${UNSAFE:-false}
max_open_connections = ${RPC_MAX_OPEN_CONNECTIONS:-900}
max_subscription_clients = ${MAX_SUBSCRIPTION_CLIENTS:-100}
max_subscriptions_per_client = ${MAX_SUBSCRIPTIONS_PER_CLIENT:-5}
timeout_broadcast_tx_commit = "${TIMEOUT_BROADCAST_TX_COMMIT:-10s}"
max_body_bytes = ${MAX_SIZE_REQUEST_BODY:-1000000}
max_header_bytes = ${MAX_SIZE_REQUEST_HEADER:-1048576}
tls_cert_file = "${TLS_CERT_FILE:-}"
tls_key_file = "${TLS_KEY_FILE:-}"


[p2p]
laddr = "${P2P_LADDR:-tcp://0.0.0.0}:${P2P_PORT:-26656}"
external_address = "${EXTERNAL_ADDRESS:-}"
seeds = "${SEEDS:-}"
persistent_peers = "${PERSISTENT_PEERS:-}"
upnp = ${UPNP:-false}
addr_book_file = "${ADDR_BOOK_FILE:-config/addrbook.json}"
addr_book_strict = ${ADDR_BOOK_STRICT:-true}
max_num_inbound_peers = ${MAX_NUM_INBOUND_PEERS:-40}
max_num_outbound_peers = ${MAX_NUM_OUTBOUND_PEERS:-10}
unconditional_peer_ids = "${UNCONDITIONAL_PEER_IDS:-}"
persistent_peers_max_dial_period = "${PERSISTENT_PEERS_MAX_DIAL_PERIOD:-0s}"
flush_throttle_timeout = "${FLUSH_THROTTLE_TIMEOUT:-100ms}"
max_packet_msg_payload_size = ${MAX_PACKET_MSG_PAYLOAD_SIZE:-1024}
send_rate = ${SEND_RATE:-5120000}
recv_rate = ${RECV_RATE:-5120000}
pex = ${PEX:-true}
seed_mode = ${SEED_MODE:-false}
private_peer_ids = "${PRIVATE_PEER_IDS:-}"
allow_duplicate_ip = ${ALLOW_DUPLICATE_IP:-false}
handshake_timeout = "${HANDSHAKE_TIMEOUT:-20s}"
dial_timeout = "${DIAL_TIMEOUT:-3s}"

[mempool]
recheck = ${RECHECK:-true}
broadcast = ${BROADCAST:-true}
wal_dir = "${WAL_DIR:-}"
size = ${SIZE_OF_MEMPOOL:-5000}
max_txs_bytes = ${MAX_TXS_BYTES:-1073741824}
cache_size = ${CACHE_SIZE:-10000}
max_tx_bytes = ${MAX_TX_BYTES:-1048576}

[fastsync]
version = "${FAST_SYNC_VERSION:-v0}"

[consensus]
wal_file = "${WAL_FILE:-data/cs.wal/wal}"
timeout_propose = "${TIMEOUT_PROPOSE:-3s}"
timeout_propose_delta = "${TIMEOUT_PROPOSE_DELTA:-500ms}"
timeout_prevote = "${TIMEOUT_PREVOTE:-1s}"
timeout_prevote_delta = "${TIMEOUT_PREVOTE_DELTA:-500ms}"
timeout_precommit = "${TIMEOUT_PRECOMMIT:-1s}"
timeout_precommit_delta = "${TIMEOUT_PRECOMMIT_DELTA:-500ms}"
timeout_commit = "${TIMEOUT_COMMIT:-5s}"
skip_timeout_commit = ${SKIP_TIMEOUT_COMMIT:-false}
create_empty_blocks = ${CREATE_EMPTY_BLOCKS:-true}
create_empty_blocks_interval = "${CREATE_EMPTY_BLOCKS_INTERVAL:-0s}"
peer_gossip_sleep_duration = "${PEER_GOSSIP_SLEEP_DURATION:-100ms}"
peer_query_maj23_sleep_duration = "${PEER_QUERY_MAJ23_SLEEP_DURATION:-2s}"

[tx_index]
indexer = "${INDEXER_SELECTION:-kv}"
# index_keys = "${INDEX_TAGS:-tx.height,tx.hash,tx.events,tx.data,tx.info}"
index_all_keys = ${INDEX_ALL_TAGS:-true}

[instrumentation]
prometheus = ${PROMETHEUS:-false}
prometheus_listen_addr = ":${PROMETHEUS_LISTEN_ADDR:-26660}"
max_open_connections = ${MAX_OPEN_CONNECTIONS:-3}
namespace = "${NAMESPACE:-tendermint}"
EOF


echo "generating app.toml"

cat > app.toml << EOF
minimum-gas-prices = "${MINIMUM_GAS_PRICES:-}"
halt-height = ${HALT_HEIGHT:-0}
halt-time = ${HALT_TIME:-0}
inter-block-cache = ${INTER_BLOCK_CACHE:-true}
pruning = "${PRUNING:-nothing}"
EOF



cd $KVD_HOME

  if [ "$BOOTSTRAP" == "TRUE" ]; then
    wget https://get.quicksync.io/kava-3-archive.20200929.0105.tar.lz4
    lz4 -d -v --rm kava-3-archive.20200929.0105.tar.lz4 | tar xf -
  fi

fi


echo "updating supervisor config files"
rm /etc/supervisor/conf.d/supervisor-kvcli.conf
rm /etc/supervisor/conf.d/supervisor-kvd.conf

cd /etc/supervisor/conf.d/

cat > supervisor-kvcli.conf << EOF
[program:kvcli]
command=kvcli rest-server --laddr tcp://0.0.0.0:${LCD_PORT:-1317} --home=${KVD_HOME:-/.kvd} --chain-id=${CHAIN_ID:-kava-4} --trust-node --node=${RPC_LADDR:-tcp://0.0.0.0}:${RPC_PORT:-26657}
redirect_stderr=false
autostart=true
autorestart=unexpected
startsecs=10
startretries=5
stdout_logfile=/stdout-kvcli.txt
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stdout_capture_maxbytes=10MB
stdout_events_enabled=false
stderr_logfile=/stderr-kvcli.txt
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=10
stderr_capture_maxbytes=10MB
stderr_events_enabled=false
EOF

cat > supervisor-kvd.conf << EOF
[program:kvd]
command=kvd start --home=${KVD_HOME:-/.kvd}
redirect_stderr=false
autostart=true
autorestart=unexpected
startsecs=10
startretries=5
stdout_logfile=/stdout-kvd.txt
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stdout_capture_maxbytes=10MB
stdout_events_enabled=false
stderr_logfile=/stderr-kvd.txt
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=10
stderr_capture_maxbytes=10MB
stderr_events_enabled=false
EOF


echo "configuration complete  ---- starting..."
exec supervisord --nodaemon --configuration /etc/supervisor/supervisord.conf
